### ISSUE TITLE
Unsafe.allocateMemory based storage 

### ISSUE THREAD

**Issue by raffaeleguidi** [raffaeleguidi/DirectMemory#37]
Thanks to @fujohnwang suggestion "ByteBuffer.allocateDirect(2g) takes more than 20 seconds as I tested - Unsafe.allocateMemory(5g) takes only 1 milliseconds or less"

**Comment by fujohnwang** [comment]
this is mostly a problem for applications that will allocate and retrieve the memory frequently, I think, but for a cache, it can allocate once and manage it until stop.

**Comment by raffaeleguidi** [comment]
Yes, this is the strategy I'm using now, but, some refactorings ago (I made at least 3 complete rewrites before getting the design done as I expected!)  I tried allocating memory on-demand for each entry, but could not allocate as much memory and not as fast as I needed. I Will try to rebuild it with Unsafe.allocateMemory and see if it works any better

**Comment by raffaeleguidi** [comment]
Initial implementation done, still buggy

**Comment by raffaeleguidi** [comment]
No go, the bottleneck with DirectBuffers is just initial allocation and this is now done initially only once for large buffers that  get later "sliced" in smaller pieces (and indexed by a guava map) - much efficient
